Repository akkadotnet/akka.net, pull requests merged in 2018-05, with the labels that each got.

#3441 Use correctly packaged verion of FSharp.Quotations nuget package
  src/core/Akka.FSharp/Akka.FSharp.fsproj
Labels: needs review

#3451 Minor fix to the Persistence Query sample code
  docs/articles/persistence/persistence-query.md
Labels: docs, reviewed positively

#3439 upgraded to DotNetty v0.4.8
  src/core/Akka.Remote/Akka.Remote.csproj
  src/core/Akka.Remote/Transport/DotNetty/TcpTransport.cs
Labels: tests

#3421 Port Pulse, DelayFlow and Valve streams-contrib stages
  src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
  src/core/Akka.Streams.Tests/Dsl/DelayFlowSpec.cs
  src/core/Akka.Streams.Tests/Dsl/PulseSpec.cs
  src/core/Akka.Streams.Tests/Dsl/ValveSpec.cs
  src/core/Akka.Streams/Dsl/DelayFlow.cs
  src/core/Akka.Streams/Dsl/Pulse.cs
  src/core/Akka.Streams/Dsl/Sample.cs
  src/core/Akka.Streams/Dsl/Valve.cs
Labels: addressed remarks, akka-streams, enhancement

#3467 just block until lock is available inside BlockingQueue
  src/core/Akka/Dispatch/MessageQueues/BlockingMessageQueue.cs
Labels: reviewed positively

#3476 Akka.Streams: add PreMaterialize support for Sources
  docs/articles/streams/basics.md
  docs/examples/DocsExamples/Streams/FlowDocTests.cs
  docs/examples/Tutorials/Tutorials.csproj
  src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
  src/core/Akka.Streams.Tests/Dsl/SourceSpec.cs
  src/core/Akka.Streams/Dsl/Source.cs
Labels: akka-streams

#3475 Introducing BenchmarkDotNet benchmarks
  src/Akka.sln
  src/benchmark/Akka.Benchmarks/Actor/ActorPathBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Actor/AddressBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Actor/PingPongBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Actor/SpawnActorBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Akka.Benchmarks.csproj
  src/benchmark/Akka.Benchmarks/Configurations/Configs.cs
  src/benchmark/Akka.Benchmarks/Hocon/HoconBenchmarks.cs
  src/benchmark/Akka.Benchmarks/IO/ByteStringBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Program.cs
  src/benchmark/Akka.Benchmarks/Serialization/SerializationBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Streams/MaterializationBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Utils/ConsistentHashBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Utils/FastLazyBenchmarks.cs
  src/benchmark/Akka.Benchmarks/Utils/TypeExtensionsBenchmarks.cs
  src/core/Akka.API.Tests/CoreAPISpec.ApproveCore.approved.txt
  src/core/Akka.API.Tests/CoreAPISpec.ApproveStreams.approved.txt
  src/core/Akka.Streams/Properties/AssemblyInfo.cs
  src/core/Akka/Properties/AssemblyInfo.cs
Labels: needs review
